FROM node:18-alpine

WORKDIR /app

# Copier les fichiers de dépendances
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le code source
COPY src ./src

# Exposer le port
EXPOSE 3000

# Commande de démarrage
CMD ["node", "src/server.js"]
