version: '3.8'

services:
  # Service Base de données PostgreSQL
  db:
    image: postgres:15
    container_name: bkn_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bkn_app
      POSTGRES_USER: bkn_user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - bkn_network

  # Service Backend Laravel
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bkn_api
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/var/www
    depends_on:
      - db
    networks:
      - bkn_network


volumes:
  db_data:

networks:
  bkn_network:
    driver: bridge
