services:
  # --- BASE DE DONNÉES ---
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: laravel_db
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: laravel_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U laravel_user -d laravel_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- BACKEND (LARAVEL) ---
  backend:
    build:
      context: ./back-laravel
      dockerfile: Dockerfile
    container_name: laravel_backend
    volumes:
      - ./back-laravel:/var/www/html
    ports:
      - "8001:8001"
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: laravel_db
      DB_USERNAME: laravel_user
      DB_PASSWORD: laravel_password
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
